import{useEffect,useState}from'react';
import{ArrowUpRight,CheckCircle2,Database,FileSearch2,Home,LockKeyhole,RefreshCw,Search,ShieldCheck,Wallet}from'lucide-react';
import type{CalldataEncodable}from'genlayer-js/types';
import{CONTRACT,configured,connectWallet,explorer,genToWei,readFinalized,short,txUrl,writeFinalized}from'./genlayer';
type Log={label:string;hash:string};type Route='/'|'/console'|'/search'|'/reviews';
const fixture={cik:'0000320193',accession:'0001140361-25-025275',document:'ef20051741_8k.htm',digest:'79d278b5c34a40ec5618d5286c983120346ebb58ccd8587339533b88e7f22e37'};
const cleanRoute=():Route=>{const p=window.location.pathname.replace(/\/$/,'')||'/';return(['/','/console','/search','/reviews'].includes(p)?p:'/') as Route};
function go(path:Route){history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'))}
function NavLink({to,children}:{to:Route;children:React.ReactNode}){return <a href={to} onClick={e=>{e.preventDefault();go(to)}}>{children}</a>}
export default function App(){
 const[route,setRoute]=useState<Route>(cleanRoute());const[account,setAccount]=useState('');const[protocol,setProtocol]=useState<any>(null);const[totals,setTotals]=useState<any>(null);const[bounty,setBounty]=useState<any>(null);const[submission,setSubmission]=useState<any>(null);const[busy,setBusy]=useState('');const[error,setError]=useState('');const[logs,setLogs]=useState<Log[]>([]);const[bountyId,setBountyId]=useState('1');const[submissionId,setSubmissionId]=useState('1');const[amount,setAmount]=useState('0.02');const[query,setQuery]=useState('1');const[searchResult,setSearchResult]=useState<any>(null);
 useEffect(()=>{const onPop=()=>setRoute(cleanRoute());window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop)},[]);
 const sync=async()=>{if(!configured)return;setError('');try{const[p,t,b,s]=await Promise.all([readFinalized<any>('get_protocol'),readFinalized<any>('get_totals'),Number(bountyId)>0?readFinalized<any>('get_bounty',[Number(bountyId)]):null,Number(submissionId)>0?readFinalized<any>('get_submission',[Number(submissionId)]):null]);setProtocol(p);setTotals(t);setBounty(b);setSubmission(s)}catch(e){setError(e instanceof Error?e.message:String(e))}};
 useEffect(()=>{void sync()},[]);
 const connect=async()=>{setError('');try{setAccount(await connectWallet())}catch(e){setError(e instanceof Error?e.message:String(e))}};
 const send=async(label:string,fn:string,args:CalldataEncodable[],value=0n)=>{setBusy(label);setError('');try{if(!account)throw Error('Connect and verify a wallet before signing.');const hash=await writeFinalized(account,fn,args,value);setLogs(v=>[{label,hash},...v]);await sync()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}};
 const search=async()=>{setError('');const id=Number(query);if(!Number.isInteger(id)||id<1)return setError('Enter a positive numeric ID.');try{const[b,s]=await Promise.all([readFinalized<any>('get_bounty',[id]),readFinalized<any>('get_submission',[id])]);setSearchResult({id,bounty:b,submission:s})}catch(e){setError(e instanceof Error?e.message:String(e))}};
 const create=()=>send('Create bounty','create_bounty',['COO succession disclosure',"Confirm a planned COO succession naming the successor and the outgoing executive's transition duties.",fixture.cik,'8-K',1700000000,1800000000,86400,600],genToWei(amount));const submit=()=>send('Submit filing','submit_filing',[Number(bountyId),fixture.accession,fixture.document,fixture.digest]);const assess=()=>send('Assess evidence','assess_submission',[Number(submissionId),Number(submission?.revision||1)]);const finalize=()=>send('Finalize payout','finalize_match',[Number(submissionId)]);const recover=()=>send('Recover bounty','recover_bounty',[Number(bountyId)]);
 return <><header><NavLink to="/"><span className="brand"><img src="/disclosure-latch-logo.png"/><span>DisclosureLatch<small>SEC filing disclosure bounties</small></span></span></NavLink><nav><NavLink to="/"><Home size={15}/>Home</NavLink><NavLink to="/console">Console</NavLink><NavLink to="/search"><Search size={15}/>ID search</NavLink><NavLink to="/reviews">Review explorer</NavLink></nav><div className="network"><i/>Studio Next 61997</div><button className="ghost" onClick={connect}><Wallet size={16}/>{account?short(account):'Connect wallet'}</button></header>{error&&<div className="globalError error">{error}</div>}
 {route==='/'&&<HomePage totals={totals} protocol={protocol}/>}
 {route==='/console'&&<main><section className="console"><div className="consoleHead"><div><p className="eyebrow">LIVE CONTRACT CONSOLE</p><h2>Run the filing lifecycle</h2></div><button className="ghost" onClick={sync}><RefreshCw size={16}/>Sync finalized state</button></div>{!configured&&<div className="notice">Contract is not configured.</div>}<div className="grid"><div className="panel"><h3>Sponsor desk</h3><label>Bounty amount in GEN<input value={amount} onChange={e=>setAmount(e.target.value)}/></label><div className="fixture"><b>Locked requirement</b><p>Confirm a planned COO succession naming the successor and transition duties.</p><code>CIK {fixture.cik} | Form 8-K</code></div><button disabled={!configured||!!busy} className="primary wide" onClick={create}>{busy==='Create bounty'?'Finalizing...':'Create funded bounty'}</button><button disabled={!configured||!!busy} className="danger wide" onClick={recover}>Recover when eligible</button></div><div className="panel"><h3>Hunter desk</h3><label>Bounty ID<input value={bountyId} onChange={e=>setBountyId(e.target.value)}/></label><div className="fixture"><b>Canonical SEC fixture</b><code>{fixture.accession}</code><small>{fixture.document}</small></div><button disabled={!configured||!!busy} className="primary wide" onClick={submit}>Submit filing</button><label>Submission ID<input value={submissionId} onChange={e=>setSubmissionId(e.target.value)}/></label><div className="twins"><button disabled={!configured||!!busy} className="ghost" onClick={assess}>Assess</button><button disabled={!configured||!!busy} className="ghost" onClick={finalize}>Finalize</button></div></div><StatePanel bounty={bounty} submission={submission} logs={logs}/></div></section></main>}
 {route==='/search'&&<main><section className="page"><p className="eyebrow">GLOBAL CONTRACT INDEX</p><h1>Search every record by ID</h1><p className="lead">One query checks both bounty and submission namespaces against finalized state.</p><div className="searchBox"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void search()} placeholder="Numeric ID"/><button className="primary" onClick={search}><Search size={17}/>Search finalized state</button></div>{searchResult&&<div className="resultGrid"><Record title={`Bounty #${searchResult.id}`} value={searchResult.bounty}/><Record title={`Submission #${searchResult.id}`} value={searchResult.submission}/></div>}</section></main>}
 {route==='/reviews'&&<main><section className="page"><p className="eyebrow">DEDICATED REVIEW EXPLORER</p><h1>Audit the evidence decision</h1><div className="reviewControls"><label>Bounty ID<input value={bountyId} onChange={e=>setBountyId(e.target.value)}/></label><label>Submission ID<input value={submissionId} onChange={e=>setSubmissionId(e.target.value)}/></label><button className="primary" onClick={sync}><RefreshCw size={16}/>Load review</button></div><div className="reviewGrid"><Record title="Bounty authorization" value={bounty}/><Record title="Submission verdict" value={submission}/></div><div className="audit"><h3>Independent audit links</h3><a href={`https://www.sec.gov/Archives/edgar/data/${Number(bounty?.cik||fixture.cik)}/${String(submission?.accession||fixture.accession).replaceAll('-','')}/${submission?.primary_document||fixture.document}`} target="_blank">Open canonical SEC document <ArrowUpRight size={15}/></a>{explorer&&<a href={explorer} target="_blank">Open contract explorer <ArrowUpRight size={15}/></a>}<p>Verdict digest: <code>{submission?.verdict_digest||'Not available'}</code></p><p>Evidence digest: <code>{submission?.evidence_digest||submission?.expected_sha256||'Not available'}</code></p></div></section></main>}
 <footer><span>DisclosureLatch</span><p>Official SEC evidence. Permissionless roles. Real Studio Next custody.</p></footer></>}
function HomePage({totals,protocol}:{totals:any;protocol:any}){return <main><section className="hero"><div><p className="eyebrow">AUTHORITATIVE DISCLOSURE, CONSENSUS VERIFIED</p><h1>Turn public filings into<br/><em>payable proof.</em></h1><p className="lead">Fund a precise disclosure question. Submit one immutable SEC accession. GenLayer validators decide whether the official filing satisfies the locked requirement.</p><div className="heroActions"><button onClick={()=>go('/console')} className="primary">Open evidence console <ArrowUpRight size={18}/></button><button onClick={()=>go('/reviews')} className="ghost">Explore reviews</button></div></div><div className="heroCard"><img src="/disclosure-latch-logo.png"/><div className="proof"><ShieldCheck/><span>Authority</span><b>SEC EDGAR</b></div><div className="proof"><Database/><span>Binding</span><b>CIK + accession</b></div><div className="proof"><LockKeyhole/><span>Consequence</span><b>GEN payout</b></div></div></section><section className="strip"><div><b>{totals?.bounties||'0'}</b><span>Bounties</span></div><div><b>{totals?.submissions||'0'}</b><span>Submissions</span></div><div><b>{totals?`${Number(totals.locked_wei)/1e18} GEN`:'0 GEN'}</b><span>Locked custody</span></div><div><b>{protocol?.version||'3'}</b><span>Protocol version</span></div></section><section className="section"><p className="eyebrow">HOW IT WORKS</p><h2>One canonical path. No arbitrary evidence URLs.</h2><div className="steps"><article><span>01</span><LockKeyhole/><h3>Lock the question</h3><p>Sponsor funds an exact semantic requirement, company CIK, form and filing window.</p></article><article><span>02</span><FileSearch2/><h3>Submit accession</h3><p>Hunter supplies only SEC identifiers and an exact content digest.</p></article><article><span>03</span><CheckCircle2/><h3>Consensus decides</h3><p>Validators verify provenance and content before GEN leaves custody.</p></article></div></section></main>}
function StatePanel({bounty,submission,logs}:{bounty:any;submission:any;logs:Log[]}){return <div className="panel state"><h3>Authoritative state</h3><dl><dt>Contract</dt><dd>{short(CONTRACT)}</dd><dt>Sponsor</dt><dd>{short(bounty?.sponsor||'')}</dd><dt>Claimant</dt><dd>{short(submission?.claimant||'')}</dd><dt>Bounty</dt><dd>{bounty?.status||'Not loaded'}</dd><dt>Submission</dt><dd>{submission?.status||'Not loaded'}</dd><dt>Reason</dt><dd>{submission?.reason||'None'}</dd></dl><div className="logs">{logs.map(x=><a key={x.hash} href={txUrl(x.hash)} target="_blank"><span>{x.label}</span><code>{short(x.hash)}</code></a>)}</div></div>}
function Record({title,value}:{title:string;value:any}){const entries=value&&Object.keys(value).length?Object.entries(value):[];return <article className="record"><h3>{title}</h3>{entries.length?<dl>{entries.map(([k,v])=><div className="recordRow" key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{String(v)}</dd></div>)}</dl>:<p>No record found.</p>}</article>}
