import{useEffect,useState}from'react';
import{ArrowUpRight,CheckCircle2,Database,FileSearch2,Home,LockKeyhole,RefreshCw,Search,ShieldCheck,Wallet}from'lucide-react';
import type{CalldataEncodable}from'genlayer-js/types';
import{CONTRACT,configured,connectWallet,explorer,genToWei,readFinalized,short,txUrl,writeFinalized}from'./genlayer';
import'./explorer.css';
type Log={label:string;hash:string};type Route='/'|'/console'|'/search'|'/reviews';
const fixture={cik:'0000320193',accession:'0001140361-25-025275',document:'ef20051741_8k.htm',digest:'79d278b5c34a40ec5618d5286c983120346ebb58ccd8587339533b88e7f22e37'};
const cleanRoute=():Route=>{const p=window.location.pathname.replace(/\/$/,'')||'/';return(['/','/console','/search','/reviews'].includes(p)?p:'/') as Route};
function go(path:Route){history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'))}
function NavLink({to,children}:{to:Route;children:React.ReactNode}){return <a href={to} onClick={e=>{e.preventDefault();go(to)}}>{children}</a>}
export default function App(){
 const[route,setRoute]=useState<Route>(cleanRoute());const[account,setAccount]=useState('');const[protocol,setProtocol]=useState<any>(null);const[totals,setTotals]=useState<any>(null);const[bounty,setBounty]=useState<any>(null);const[submission,setSubmission]=useState<any>(null);const[bounties,setBounties]=useState<any[]>([]);const[submissions,setSubmissions]=useState<any[]>([]);const[indexBusy,setIndexBusy]=useState(false);const[busy,setBusy]=useState('');const[error,setError]=useState('');const[logs,setLogs]=useState<Log[]>([]);const[bountyId,setBountyId]=useState('1');const[submissionId,setSubmissionId]=useState('1');const[amount,setAmount]=useState('0.02');const[query,setQuery]=useState('');const[statusFilter,setStatusFilter]=useState('ALL');
 useEffect(()=>{const onPop=()=>setRoute(cleanRoute());window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop)},[]);
 const loadIndex=async(t:any)=>{setIndexBusy(true);try{const bc=Math.min(Number(t?.bounties||0),100),sc=Math.min(Number(t?.submissions||0),200);const[bs,ss]=await Promise.all([Promise.all(Array.from({length:bc},(_,i)=>readFinalized<any>('get_bounty',[i+1]))),Promise.all(Array.from({length:sc},(_,i)=>readFinalized<any>('get_submission',[i+1])))]);setBounties(bs.filter(x=>x&&Object.keys(x).length));setSubmissions(ss.filter(x=>x&&Object.keys(x).length));return{bs,ss}}finally{setIndexBusy(false)}};
 const sync=async()=>{if(!configured)return;setError('');try{const[p,t]=await Promise.all([readFinalized<any>('get_protocol'),readFinalized<any>('get_totals')]);setProtocol(p);setTotals(t);const{bs,ss}=await loadIndex(t);const bid=Number(bountyId),sid=Number(submissionId);setBounty(bs.find((x:any)=>Number(x.id)===bid)||null);setSubmission(ss.find((x:any)=>Number(x.id)===sid)||null)}catch(e){setError(e instanceof Error?e.message:String(e))}};
 useEffect(()=>{void sync()},[]);
 const connect=async()=>{setError('');try{setAccount(await connectWallet())}catch(e){setError(e instanceof Error?e.message:String(e))}};
 const send=async(label:string,fn:string,args:CalldataEncodable[],value=0n)=>{setBusy(label);setError('');try{if(!account)throw Error('Connect and verify a wallet before signing.');const hash=await writeFinalized(account,fn,args,value);setLogs(v=>[{label,hash},...v]);await sync()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}};
 const selectBounty=(b:any)=>{setBounty(b);setBountyId(String(b.id));const related=submissions.find(s=>Number(s.bounty_id)===Number(b.id));setSubmission(related||null);if(related)setSubmissionId(String(related.id))};const selectSubmission=(s:any)=>{setSubmission(s);setSubmissionId(String(s.id));const parent=bounties.find(b=>Number(b.id)===Number(s.bounty_id));setBounty(parent||null);if(parent)setBountyId(String(parent.id))};
 const needle=query.trim().toLowerCase();const matches=(x:any)=>!needle||Object.values(x||{}).some(v=>String(v).toLowerCase().includes(needle));const visibleBounties=bounties.filter(b=>matches(b)&&(statusFilter==='ALL'||b.status===statusFilter));const visibleSubmissions=submissions.filter(s=>matches(s)&&(statusFilter==='ALL'||s.status===statusFilter));
 const create=()=>send('Create bounty','create_bounty',['COO succession disclosure',"Confirm a planned COO succession naming the successor and the outgoing executive's transition duties.",fixture.cik,'8-K',1700000000,1800000000,86400,600],genToWei(amount));const submit=()=>send('Submit filing','submit_filing',[Number(bountyId),fixture.accession,fixture.document,fixture.digest]);const assess=()=>send('Assess evidence','assess_submission',[Number(submissionId),Number(submission?.revision||1)]);const finalize=()=>send('Finalize payout','finalize_match',[Number(submissionId)]);const recover=()=>send('Recover bounty','recover_bounty',[Number(bountyId)]);
 return <><header><NavLink to="/"><span className="brand"><img src="/disclosure-latch-logo.png"/><span>DisclosureLatch<small>SEC filing disclosure bounties</small></span></span></NavLink><nav><NavLink to="/"><Home size={15}/>Home</NavLink><NavLink to="/console">Console</NavLink><NavLink to="/search"><Search size={15}/>Browse records</NavLink><NavLink to="/reviews">Review explorer</NavLink></nav><div className="network"><i/>Studio Next 61997</div><button className="ghost" onClick={connect}><Wallet size={16}/>{account?short(account):'Connect wallet'}</button></header>{error&&<div className="globalError error">{error}</div>}
 {route==='/'&&<HomePage totals={totals} protocol={protocol}/>}
 {route==='/console'&&<main><section className="console"><div className="consoleHead"><div><p className="eyebrow">LIVE CONTRACT CONSOLE</p><h2>Run the filing lifecycle</h2></div><button className="ghost" onClick={sync}><RefreshCw size={16}/>Sync finalized state</button></div>{!configured&&<div className="notice">Contract is not configured.</div>}<div className="grid"><div className="panel"><h3>Sponsor desk</h3><label>Bounty amount in GEN<input value={amount} onChange={e=>setAmount(e.target.value)}/></label><div className="fixture"><b>Locked requirement</b><p>Confirm a planned COO succession naming the successor and transition duties.</p><code>CIK {fixture.cik} | Form 8-K</code></div><button disabled={!configured||!!busy} className="primary wide" onClick={create}>{busy==='Create bounty'?'Finalizing...':'Create funded bounty'}</button><button disabled={!configured||!!busy||!bounty} className="danger wide" onClick={recover}>Recover selected bounty</button></div><div className="panel"><h3>Hunter desk</h3><label>Select an open bounty<select value={bountyId} onChange={e=>{const b=bounties.find(x=>String(x.id)===e.target.value);if(b)selectBounty(b)}}>{bounties.length?bounties.map(b=><option key={b.id} value={b.id}>{b.title||`Bounty ${b.id}`} · {b.status}</option>):<option>No finalized bounties</option>}</select></label><div className="fixture"><b>Canonical SEC fixture</b><code>{fixture.accession}</code><small>{fixture.document}</small></div><button disabled={!configured||!!busy||!bounty} className="primary wide" onClick={submit}>Submit filing</button><label>Select a filing submission<select value={submissionId} onChange={e=>{const s=submissions.find(x=>String(x.id)===e.target.value);if(s)selectSubmission(s)}}>{submissions.length?submissions.map(s=><option key={s.id} value={s.id}>{s.accession||`Submission ${s.id}`} · {s.status}</option>):<option>No finalized submissions</option>}</select></label><div className="twins"><button disabled={!configured||!!busy||!submission} className="ghost" onClick={assess}>Assess selected</button><button disabled={!configured||!!busy||!submission} className="ghost" onClick={finalize}>Finalize selected</button></div></div><StatePanel bounty={bounty} submission={submission} logs={logs}/></div></section></main>}
 {route==='/search'&&<main><section className="page"><p className="eyebrow">GLOBAL CONTRACT INDEX</p><h1>Browse finalized records</h1><p className="lead">Search by title, requirement, CIK, accession, wallet, form or status. No internal ID is required.</p><IndexToolbar query={query} setQuery={setQuery} status={statusFilter} setStatus={setStatusFilter} loading={indexBusy} refresh={sync}/><div className="catalog"><Catalog title="Bounties" rows={visibleBounties} kind="bounty" selected={bounty?.id} choose={selectBounty}/><Catalog title="Submissions" rows={visibleSubmissions} kind="submission" selected={submission?.id} choose={selectSubmission}/></div>{!indexBusy&&!visibleBounties.length&&!visibleSubmissions.length&&<div className="empty">No finalized records match this search.</div>}</section></main>}
 {route==='/reviews'&&<main><section className="page"><p className="eyebrow">DEDICATED REVIEW EXPLORER</p><h1>Choose a decision to audit</h1><p className="lead">Select a filing submission from finalized contract history. Its parent bounty is resolved automatically.</p><IndexToolbar query={query} setQuery={setQuery} status={statusFilter} setStatus={setStatusFilter} loading={indexBusy} refresh={sync}/><div className="reviewBrowser"><div className="reviewList"><h3>Filing submissions <span>{visibleSubmissions.length}</span></h3>{visibleSubmissions.map(s=><button key={s.id} className={Number(submission?.id)===Number(s.id)?'selected':''} onClick={()=>selectSubmission(s)}><div><b>{s.accession||`Submission ${s.id}`}</b><small>{s.primary_document} · Bounty {s.bounty_id}</small></div><em>{s.status}</em></button>)}{!visibleSubmissions.length&&!indexBusy&&<p className="empty">No submissions match the current filters.</p>}</div><div className="reviewDetail">{submission?<><div className="reviewGrid"><Record title="Bounty authorization" value={bounty}/><Record title="Submission verdict" value={submission}/></div><div className="audit"><h3>Independent audit links</h3><a href={`https://www.sec.gov/Archives/edgar/data/${Number(bounty?.cik||fixture.cik)}/${String(submission.accession||fixture.accession).replaceAll('-','')}/${submission.primary_document||fixture.document}`} target="_blank">Open canonical SEC document <ArrowUpRight size={15}/></a>{explorer&&<a href={explorer} target="_blank">Open contract explorer <ArrowUpRight size={15}/></a>}<p>Verdict digest: <code>{submission.verdict_digest||'Not available'}</code></p><p>Evidence digest: <code>{submission.evidence_digest||submission.expected_sha256||'Not available'}</code></p></div></>:<div className="empty">Select a submission to inspect its authorization, verdict, evidence and audit links.</div>}</div></div></section></main>}
 <footer><span>DisclosureLatch</span><p>Official SEC evidence. Permissionless roles. Real Studio Next custody.</p></footer></>}
function HomePage({totals,protocol}:{totals:any;protocol:any}){return <main><section className="hero"><div><p className="eyebrow">AUTHORITATIVE DISCLOSURE, CONSENSUS VERIFIED</p><h1>Turn public filings into<br/><em>payable proof.</em></h1><p className="lead">Fund a precise disclosure question. Submit one immutable SEC accession. GenLayer validators decide whether the official filing satisfies the locked requirement.</p><div className="heroActions"><button onClick={()=>go('/console')} className="primary">Open evidence console <ArrowUpRight size={18}/></button><button onClick={()=>go('/reviews')} className="ghost">Explore reviews</button></div></div><div className="heroCard"><img src="/disclosure-latch-logo.png"/><div className="proof"><ShieldCheck/><span>Authority</span><b>SEC EDGAR</b></div><div className="proof"><Database/><span>Binding</span><b>CIK + accession</b></div><div className="proof"><LockKeyhole/><span>Consequence</span><b>GEN payout</b></div></div></section><section className="strip"><div><b>{totals?.bounties||'0'}</b><span>Bounties</span></div><div><b>{totals?.submissions||'0'}</b><span>Submissions</span></div><div><b>{totals?`${Number(totals.locked_wei)/1e18} GEN`:'0 GEN'}</b><span>Locked custody</span></div><div><b>{protocol?.version||'3'}</b><span>Protocol version</span></div></section><section className="section"><p className="eyebrow">HOW IT WORKS</p><h2>One canonical path. No arbitrary evidence URLs.</h2><div className="steps"><article><span>01</span><LockKeyhole/><h3>Lock the question</h3><p>Sponsor funds an exact semantic requirement, company CIK, form and filing window.</p></article><article><span>02</span><FileSearch2/><h3>Submit accession</h3><p>Hunter supplies only SEC identifiers and an exact content digest.</p></article><article><span>03</span><CheckCircle2/><h3>Consensus decides</h3><p>Validators verify provenance and content before GEN leaves custody.</p></article></div></section></main>}
function StatePanel({bounty,submission,logs}:{bounty:any;submission:any;logs:Log[]}){return <div className="panel state"><h3>Authoritative state</h3><dl><dt>Contract</dt><dd>{short(CONTRACT)}</dd><dt>Sponsor</dt><dd>{short(bounty?.sponsor||'')}</dd><dt>Claimant</dt><dd>{short(submission?.claimant||'')}</dd><dt>Bounty</dt><dd>{bounty?.status||'Not loaded'}</dd><dt>Submission</dt><dd>{submission?.status||'Not loaded'}</dd><dt>Reason</dt><dd>{submission?.reason||'None'}</dd></dl><div className="logs">{logs.map(x=><a key={x.hash} href={txUrl(x.hash)} target="_blank"><span>{x.label}</span><code>{short(x.hash)}</code></a>)}</div></div>}
function IndexToolbar({query,setQuery,status,setStatus,loading,refresh}:{query:string;setQuery:(v:string)=>void;status:string;setStatus:(v:string)=>void;loading:boolean;refresh:()=>void}){return <div className="indexToolbar"><label className="indexSearch"><Search size={18}/><input aria-label="Search finalized records" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title, CIK, accession, wallet or status…"/></label><select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option><option value="OPEN">Open</option><option value="CLAIMED">Claimed</option><option value="MATCH">Match</option><option value="NO_MATCH">No match</option><option value="PAID">Paid</option><option value="REFUNDED">Refunded</option></select><button className="ghost" onClick={refresh} disabled={loading}><RefreshCw size={16} className={loading?'spin':''}/>{loading?'Indexing…':'Refresh index'}</button></div>}
function Catalog({title,rows,kind,selected,choose}:{title:string;rows:any[];kind:'bounty'|'submission';selected:any;choose:(x:any)=>void}){return <section className="catalogGroup"><div className="catalogHead"><h3>{title}</h3><span>{rows.length} finalized</span></div><div className="catalogRows">{rows.map(x=><button key={x.id} onClick={()=>choose(x)} className={Number(selected)===Number(x.id)?'selected':''}><span className="recordIcon">{kind==='bounty'?'B':'S'}</span><div><b>{kind==='bounty'?(x.title||`Bounty ${x.id}`):(x.accession||`Submission ${x.id}`)}</b><small>{kind==='bounty'?`${x.form_type||'Form'} · CIK ${x.cik||'—'}`:`${x.primary_document||'Filing'} · ${short(x.claimant||'')}`}</small></div><em>{x.status||'UNKNOWN'}</em><ArrowUpRight size={15}/></button>)}</div></section>}
function Record({title,value}:{title:string;value:any}){const entries=value&&Object.keys(value).length?Object.entries(value):[];return <article className="record"><h3>{title}</h3>{entries.length?<dl>{entries.map(([k,v])=><div className="recordRow" key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{String(v)}</dd></div>)}</dl>:<p>No record found.</p>}</article>}
