import{useEffect,useRef,useState}from'react';import{ArrowUpRight,CheckCircle2,Database,FileSearch2,LockKeyhole,RefreshCw,ShieldCheck,Wallet}from'lucide-react';import type{CalldataEncodable,TransactionHash}from'genlayer-js/types';import{CONTRACT,configured,explorer,genToWei,normalizeTx,reader,short,txUrl,writer}from'./genlayer';

type Log={label:string;hash:string};
const fixture={cik:'0000320193',accession:'0001140361-25-025275',document:'ef20051741_8k.htm',digest:'79d278b5c34a40ec5618d5286c983120346ebb58ccd8587339533b88e7f22e37'};
export default function App(){
 const[account,setAccount]=useState('');const[protocol,setProtocol]=useState<any>(null);const[totals,setTotals]=useState<any>(null);const[bounty,setBounty]=useState<any>(null);const[submission,setSubmission]=useState<any>(null);const[busy,setBusy]=useState('');const[error,setError]=useState('');const[logs,setLogs]=useState<Log[]>([]);
 const[bountyId,setBountyId]=useState('1');const[submissionId,setSubmissionId]=useState('1');const[amount,setAmount]=useState('0.02');
 const syncSeq=useRef(0);
 const sync=async()=>{if(!configured)return;const seq=++syncSeq.current;setError('');const read=async(fn:string,args:CalldataEncodable[]=[])=>{let failure:unknown;for(let attempt=0;attempt<3;attempt++){try{return await reader.readContract({address:CONTRACT,functionName:fn,args,jsonSafeReturn:true})}catch(e){failure=e;if(attempt<2)await new Promise(r=>window.setTimeout(r,800*(attempt+1)))}}throw failure};try{const bid=Number(bountyId),sid=Number(submissionId);const p=await read('get_protocol'),t=await read('get_totals'),b=bid>0?await read('get_bounty',[bid]):null,s=sid>0?await read('get_submission',[sid]):null;if(seq!==syncSeq.current)return;setProtocol(p);setTotals(t);setBounty(b);setSubmission(s)}catch(e){if(seq===syncSeq.current)setError(e instanceof Error?e.message:String(e))}};
 useEffect(()=>{void sync()},[]);
 const connect=async()=>{if(!window.ethereum)return setError('No injected wallet found.');const a=await window.ethereum.request({method:'eth_requestAccounts'}) as string[];setAccount(a[0]||'')};
 const send=async(label:string,fn:string,args:CalldataEncodable[],value=0n)=>{setBusy(label);setError('');try{const client=writer();const fees=await client.estimateTransactionFees({});const tx=normalizeTx(await client.writeContract({address:CONTRACT,functionName:fn,args,value,fees}));setLogs(v=>[{label,hash:tx},...v]);await reader.waitForTransactionReceipt({hash:tx as TransactionHash,waitUntil:'finalized',interval:4000,retries:300});await sync()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}};
 const create=()=>send('Create bounty','create_bounty',['COO succession disclosure',"Confirm a planned COO succession naming the successor and the outgoing executive's transition duties.",fixture.cik,'8-K',1700000000,1800000000,86400,600],genToWei(amount));
 const submit=()=>send('Submit filing','submit_filing',[Number(bountyId),fixture.accession,fixture.document,fixture.digest]);
 const assess=()=>send('Assess evidence','assess_submission',[Number(submissionId),Number(submission?.revision||1)]);
 const finalize=()=>send('Finalize payout','finalize_match',[Number(submissionId)]);const recover=()=>send('Recover bounty','recover_bounty',[Number(bountyId)]);
 return <><header><a className="brand" href="#top"><img src="/disclosure-latch-logo.png"/><span>DisclosureLatch<small>SEC filing disclosure bounties</small></span></a><div className="network"><i/>Studio Next 61997</div><button className="ghost" onClick={connect}><Wallet size={16}/>{account?short(account):'Connect wallet'}</button></header>
 <main id="top"><section className="hero"><div><p className="eyebrow">AUTHORITATIVE DISCLOSURE, CONSENSUS VERIFIED</p><h1>Turn public filings into<br/><em>payable proof.</em></h1><p className="lead">Fund a precise disclosure question. Submit one immutable SEC accession. GenLayer validators decide whether the official filing satisfies the locked requirement.</p><div className="heroActions"><a href="#console" className="primary">Open evidence console <ArrowUpRight size={18}/></a>{explorer&&<a href={explorer} target="_blank" className="link">View contract</a>}</div></div><div className="heroCard"><img src="/disclosure-latch-logo.png"/><div className="proof"><ShieldCheck/><span>Authority</span><b>SEC EDGAR</b></div><div className="proof"><Database/><span>Binding</span><b>CIK + accession</b></div><div className="proof"><LockKeyhole/><span>Consequence</span><b>GEN payout</b></div></div></section>
 <section className="strip"><div><b>{totals?.bounties||'0'}</b><span>Bounties</span></div><div><b>{totals?.submissions||'0'}</b><span>Filings assessed</span></div><div><b>{totals?`${Number(totals.locked_wei)/1e18} GEN`:'0 GEN'}</b><span>Locked custody</span></div><div><b>{protocol?.version||'1'}</b><span>Protocol version</span></div></section>
 <section className="section"><p className="eyebrow">HOW IT WORKS</p><h2>One canonical path. No arbitrary evidence URLs.</h2><div className="steps"><article><span>01</span><LockKeyhole/><h3>Lock the question</h3><p>Sponsor funds an exact semantic requirement, company CIK, form and filing window.</p></article><article><span>02</span><FileSearch2/><h3>Submit accession</h3><p>Hunter supplies only SEC identifiers and an exact content digest. The contract constructs the source.</p></article><article><span>03</span><CheckCircle2/><h3>Consensus decides</h3><p>Validators verify provenance and content before any GEN can leave custody.</p></article></div></section>
 <section className="console" id="console"><div className="consoleHead"><div><p className="eyebrow">LIVE CONTRACT CONSOLE</p><h2>Review the filing lifecycle</h2></div><button className="ghost" onClick={sync}><RefreshCw size={16}/>Sync state</button></div>{!configured&&<div className="notice">Contract deployment pending. Add VITE_CONTRACT_ADDRESS after deploying the exact committed source.</div>}{error&&<div className="error">{error}</div>}
 <div className="grid"><div className="panel"><h3>Sponsor desk</h3><label>Bounty amount in GEN<input value={amount} onChange={e=>setAmount(e.target.value)}/></label><div className="fixture"><b>Locked requirement</b><p>Confirm a planned COO succession naming the successor and transition duties.</p><code>CIK {fixture.cik} | Form 8-K</code></div><button disabled={!configured||!!busy} className="primary wide" onClick={create}>{busy==='Create bounty'?'Submitting...':'Create funded bounty'}</button><button disabled={!configured||!!busy} className="danger wide" onClick={recover}>Recover when eligible</button></div>
 <div className="panel"><h3>Hunter desk</h3><label>Bounty ID<input value={bountyId} onChange={e=>setBountyId(e.target.value)}/></label><div className="fixture"><b>Canonical SEC fixture</b><code>{fixture.accession}</code><small>{fixture.document}</small></div><button disabled={!configured||!!busy} className="primary wide" onClick={submit}>Submit filing</button><label>Submission ID<input value={submissionId} onChange={e=>setSubmissionId(e.target.value)}/></label><div className="twins"><button disabled={!configured||!!busy} className="ghost" onClick={assess}>Assess</button><button disabled={!configured||!!busy} className="ghost" onClick={finalize}>Finalize</button></div></div>
 <div className="panel state"><h3>Authoritative state</h3><dl><dt>Contract</dt><dd>{short(CONTRACT)}</dd><dt>Bounty sponsor</dt><dd>{short(bounty?.sponsor||'')}</dd><dt>Claimant</dt><dd>{short(submission?.claimant||'')}</dd><dt>Bounty</dt><dd>{bounty?.status||'Not loaded'}</dd><dt>Submission</dt><dd>{submission?.status||'Not loaded'}</dd><dt>Reason</dt><dd>{submission?.reason||'None'}</dd></dl><div className="logs">{logs.map(x=><a key={x.hash} href={txUrl(x.hash)} target="_blank"><span>{x.label}</span><code>{short(x.hash)}</code></a>)}</div></div></div></section>
 </main><footer><span>DisclosureLatch</span><p>Official SEC evidence. Permissionless roles. Real Studio Next custody.</p></footer></>}
