import {createAccount,createClient} from '../frontend/node_modules/genlayer-js/dist/index.js';
import {studioDevnet} from '../frontend/node_modules/genlayer-js/dist/chains/index.js';
const contract=process.env.DISCLOSURE_CONTRACT||'0x752eA1c5B3b7b192019781a6392f278a959077C9';
const acct=(n)=>{const v=process.env[n];if(!v)throw Error(`${n} required`);return createAccount(v.startsWith('0x')?v:`0x${v}`)};
const sponsor=acct('DISCLOSURE_SPONSOR_KEY'),claimant=acct('DISCLOSURE_CLAIMANT_KEY');
const s=createClient({chain:studioDevnet,account:sponsor}),c=createClient({chain:studioDevnet,account:claimant}),r=createClient({chain:studioDevnet});
const out=(v)=>JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x);
const read=(fn,args=[])=>r.readContract({address:contract,functionName:fn,args,jsonSafeReturn:true});
async function send(client,label,fn,args,value=0n){const fees=await client.estimateTransactionFees({});const hash=await client.writeContract({address:contract,functionName:fn,args,value,fees});console.log(`${label}.tx=${hash}`);await client.waitForTransactionReceipt({hash,waitUntil:'finalized',interval:4000,retries:300});const receipt=await client.getTransaction({hash});console.log(`${label}.consensus=${receipt.result_name||receipt.result}`);if(receipt.result_name!=='MAJORITY_AGREE')throw Error(`${label} consensus failed`);return hash}
const fixture=['0001140361-25-025275','ef20051741_8k.htm'];
const totals=await read('get_totals');const b2=Number(totals.bounties)+1,s2=Number(totals.submissions)+1;
await send(s,'failure_create','create_bounty',['Digest failure recovery','Confirm a planned COO succession naming the successor and the outgoing executive transition duties.','0000320193','8-K',1700000000,1800000000,86400,300],10n**16n);
await send(c,'failure_submit_bad_digest','submit_filing',[b2,...fixture,'0'.repeat(64)]);
await send(s,'failure_assess_1','assess_submission',[s2,1]);console.log(`failure_state_1=${out(await read('get_submission',[s2]))}`);
await send(c,'failure_retry','retry_unresolved',[s2,2]);
await send(s,'failure_assess_2','assess_submission',[s2,2]);console.log(`failure_state_2=${out(await read('get_submission',[s2]))}`);
await send(s,'failure_refund','recover_bounty',[b2]);console.log(`failure_bounty=${out(await read('get_bounty',[b2]))}`);
const after=await read('get_totals');const b3=Number(after.bounties)+1,s3=Number(after.submissions)+1;
await send(s,'negative_create','create_bounty',['Unrelated acquisition disclosure','Confirm that Apple disclosed a completed acquisition of a Martian mining company and transferred ownership on the filing date.','0000320193','8-K',1700000000,1800000000,86400,300],10n**16n);
await send(c,'negative_submit','submit_filing',[b3,...fixture,'79d278b5c34a40ec5618d5286c983120346ebb58ccd8587339533b88e7f22e37']);
await send(s,'negative_assess','assess_submission',[s3,1]);console.log(`negative_submission=${out(await read('get_submission',[s3]))}`);console.log(`negative_bounty=${out(await read('get_bounty',[b3]))}`);console.log(`totals=${out(await read('get_totals'))}`);
